### ISSUE TITLE
Output to stdout

### ISSUE THREAD

**Issue by benma** [thlorenz/doctoc#100]
Hi

It would be great if doctoc could also be used to figure out if the existing table of contents (generated by doctoc) is up to date.

One way would be to add an option to output the updated markdown file to stdout, instead of updating the file. The output could be diffed to the original.

Reason for the request: we have a lot of markdown files in our repo, and it would be nice if our CI could check if the table of contents have been updated.

**Comment by jez** [comment]
Closed by #111.

**Comment by benma** [comment]
Thank you!
