### ISSUE TITLE
doctoc --notitle creates a superfluous blank line

### ISSUE THREAD

**Issue by benma** [thlorenz/doctoc#101]
If I run `doctoc --notitle`, there are two consecutive blank lines instead of one. 

```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->


- [Title](#title)
- etc.
```

[markdownlint](https://github.com/mivok/markdownlint) for example complains about that.
Would it be okay to skip one of the empty lines if there is no title?

**Comment by revelt** [comment]
+1. Same thing if

    
    

is used inline without `--notitle`. I guess adding some conditional logic does title exist or not and placing less line breaks on the latter case would solve this.

**Comment by chocolateboy** [comment]
>  Would it be okay to skip one of the empty lines if there is no title?

Or always? I always end up manually removing these lines...
