### ISSUE TITLE
@ in a header

### ISSUE THREAD

**Issue by bbohling** [thlorenz/doctoc#104]
When you use `@` in a header, doctoc should remove it in the link as GitHub does.

Example:

```md
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
**Table of Contents**

- [My Cool@Header](#my-coolheader)
<!-- END doctoc generated TOC please keep comment here to allow auto update -->


## My Cool@Header

```

Instead it is currently creating a link like: `[My Cool@Header](#my-cool@header)`

**Comment by jez** [comment]
This is a super simple fix. It involves just adding an `@` to the regex [here](https://github.com/thlorenz/anchor-markdown-header/blob/master/anchor-markdown-header.js#L23)

**Comment by jez** [comment]
I've submitted a patch upstream (see reference above).

**Comment by jez** [comment]
Also, just realized this is a duplicate of #81.
