### ISSUE TITLE
Create base link for anchors

### ISSUE THREAD

**Issue by carlosdelfino** [thlorenz/doctoc#117]
Where the TOC is created I need the anchor is prefixed with a base link.

I can inform this base link in command line or it is get on `permalink`parameter from source markdown file.

And generate a similar file like this: https://github.com/carlosdelfino/micro-os-plus.github.io-source/blob/a72914859eaeb98dea13b7469a0db80432269584/pages/user-manual/basic-concepts.toc.pt.md

**Comment by jez** [comment]
Thanks for opening this @carlosdelfino. I can understand why you'd want this feature. However, I'm inclined to think that this feature is beyond the scope of this project. I think it adds too much complexity.

@thlorenz feel free to re-open if you feel otherwise.
