### ISSUE TITLE
& Symbol in Headings

### ISSUE THREAD

**Issue by RyanZim** [thlorenz/doctoc#118]
Doctoc's links do not work with github's handling of the `&` symbol.

From the heading `## CLI Usage & Options`, doctoc generates the link `#cli-usage-&-options` while GH uses `#cli-usage--options`.

You can see the bug in the wild at: https://github.com/RyanZim/onessg.

**Comment by thlorenz** [comment]
Please submit a PR in anchor-markdown-header to fix after you verify that none of [these](https://github.com/thlorenz/anchor-markdown-header/pulls) address your problem.

**Comment by RyanZim** [comment]
@thlorenz PR done: https://github.com/thlorenz/anchor-markdown-header/pull/33.
