### ISSUE TITLE
Emojis in headings break links

### ISSUE THREAD

**Issue by adrianmcli** [thlorenz/doctoc#123]
Pretty simple bug 🐞

## Steps to reproduce:

1. Put an emoji on the same line as a heading.
2. Run doctoc on it.
3. Notice that the generated link does not work.

**Comment by thlorenz** [comment]
wow, I have no idea what to do about that.
Could you tell me what the generated link should look like?

If so please refile this issue in anchor-markdown-header and we can try to fix it there.

**Comment by adrianmcli** [comment]
I tried it, and apparently it just leaves it out, but with a dash.

So I actually tried it out with a heading like this:

```
# Modules 📦
```

And the Markdown required is:

```
- [Modules](#modules-)
```

You can see it here: https://github.com/adrianmcli/next-boilerplate/blob/master/README.md

I will cross-post to anchor-markdown-header.

**Comment by adrianmcli** [comment]
Continued in https://github.com/thlorenz/anchor-markdown-header/issues/36
