### ISSUE TITLE
Would we consider migrating test suite to AVA?

### ISSUE THREAD

**Issue by revelt** [thlorenz/doctoc#124]
Currently, TAP is driving the unit tests. In my humble opinion, it's not as nice as AVA: the console output is not styled, plus we're on `~0.4.8` currently, which is outdated will need updating anyway.

Let's migrate all tests to AVA! Before spending time on fork, I wanted to discuss this with all maintainers, what do you think?

**Comment by thlorenz** [comment]
No, not considering this. If you wanna migrate to tape (which is lighter weight and does require basically no code changes) that's fine.

AVA is a huge beast of stuff of which 90% aren't important to this project, so please don't.
It adds no value and I won't merge it.

**Comment by revelt** [comment]
Fair thing, closing. Thank you for such a fast response.
