### ISSUE TITLE
Some issues slip through in unit tests

### ISSUE THREAD

**Issue by revelt** [thlorenz/doctoc#125]
Why are there no unit tests which would compare the **whole file's contents** as static string, without a variable parts?

The problem is, currently, unit tests try to compare only the inner TOC contents, between comment blocks (I'm talking about .MD files) by extracting TOC content. When that extraction is messed up, the comparison is messed up and errors slip through.

Let's review this `headers.toc.split('\n')` part:

```
t.deepEqual(
      headers.toc.split('\n')
    , [ '## Table of Contents',
```

or at least, add more tests comparing whole file contents from `/fixtures/` against a single string.

**Comment by revelt** [comment]
It looks like currently doctoc removes the titles within the comment block. Which means, it's working as intended. However, we should still have at least some unit tests that compare output files in whole, as a string.

The #101 slipped through the tests because unit tests were not comparing whole-file-contents-as-string vs. desired-string.

**Comment by thlorenz** [comment]
@revelt not fully following your discussion here, but why not submit a PR with tests that you feel are missing. At that point we'll better understand what you're talking about and can review things and hopefully pull in those tests.

If you discover a bug (via a failing test) we'd appreciate a fix.

Thanks.

**Comment by revelt** [comment]
@thlorenz Sure, please keep this ticket open, I need more time to investigate.

I migrated half of my libs readme's to include ToC, it's amazing tool by the way.
