### ISSUE TITLE
Missing items in TOC

### ISSUE THREAD

**Issue by brunofacca** [thlorenz/doctoc#129]
Thank you for this great tool, it is very useful.

When generating a TOC for https://github.com/brunofacca/zen-rails-security-checklist/blob/master/README.md,  the "Output Escaping & Sanitization" and "File Downloads" are omitted. Seems to be a bug.

**Comment by jez** [comment]
As it turns out, this is a feature, not a bug. There's a flag that controls the maximum number of levels to include in the Table of Contents. It's set to 4 levels by default.

For more information:

https://github.com/thlorenz/doctoc#specifying-a-maximum-heading-level-for-toc-entries

**Comment by brunofacca** [comment]
I don't think that was the problem. The "File Uploads" and "File Downloads" items are on the same level and only the former was included in the DOC. Same happened with the other two items ("Handling User Input" and "Output Escaping & Sanitization"), they are on the same level and only the first appears in the TOC.

**Comment by jez** [comment]
The next problem is that your Markdown is poorly formatted. Be sure to put newlines above your ATX-style (`###`) style headings.

Behavior around ATX-style headings varies from parser to parser. For example, you're allowed to have no leading newline using GitHub's Markdown parser, but not the Markdown parser we're using.

**Comment by jez** [comment]
(Not sure which text editor you use, but [vim-pandoc-syntax][1] highlights this inconsistency for me so that I get a fore-warning that undefined behavior might ensure).

[1]: https://github.com/vim-pandoc/vim-pandoc-syntax

**Comment by brunofacca** [comment]
The absence of newlines above the ATX-style (###) style headings was the problem. 

I will try vim-pandoc-syntax.

Thank you!
