### ISSUE TITLE
markdown-to-ast is deprecated

### ISSUE THREAD

**Issue by ozum** [thlorenz/doctoc#148]
Hi,

`markdown-to-ast` module seems deprecated. I get following warning during `doctoc` install:

`npm WARN deprecated markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455`

Kind Regards,

**Comment by thlorenz** [comment]
Feel free to provide a PR using an alternative parser + passing all tests and we can swap it out.
Thanks.

**Comment by MartB** [comment]
Can we get this pulled?
@thlorenz

**Comment by thlorenz** [comment]
Fixed in d003dce032c41e40546fbc68c1077aca02bb3764
