### ISSUE TITLE
doctoc resolves paths with spaces incorrectly

### ISSUE THREAD

**Issue by kalynrobinson** [thlorenz/doctoc#158]
## Bug Report

**Describe the bug**

On Windows, doctoc resolves paths with spaces incorrectly.

`doctoc "foo bar\README.md"`
> Error: ENOENT: no such file or directory, stat 'foo\ bar\README.md'

| | |
| ---- | ---- |
| **Input** | "foo bar\README.md"|
| **Expected** | "foo bar\README.md"|
| **Actual** | "foo\ bar\README.md"|

**To Reproduce**
1. Run `doctoc` against a path with a space in it
2. See error

```shell
mkdir "foo bar"
echo "**test**" > "foo bar/bazz.md"
doctoc "foo bar/bazz.md"
```

**Expected behavior**

doctoc should successfully locate file.

**Environment**

* OS: Windows 10
* Node/npm version: 
  * Yarn 1.12.3
  * Node v10.3.0

**Cause**
The function `cleanPath` in [doctoc.js](https://github.com/thlorenz/doctoc/blob/164f78e6452413a9717f58df8cf9dcb200b6c0f7/doctoc.js#L12) is attempting to escape spaces. It's my understanding that `fs` should already handle this behind the scenes.

```javascript
function cleanPath(path) {
    var homeExpanded =
        path.indexOf("~") === 0 ? process.env.HOME + path.substr(1) : path;

    // Escape all spaces
    return homeExpanded.replace(/\s/g, "\\ ");
}
```

**Comment by Shagon94** [comment]
Can confirm:

```bash
$ doctoc 'Extra Headers.md'
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'Extra\ Headers.md'
    at Object.statSync (fs.js:848:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/doctoc/doctoc.js:103:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Fix is as follows:

```js
function cleanPath(path) {
  var homeExpanded = (path.indexOf('~') === 0) ? process.env.HOME + path.substr(1) : path;

  // Escape all spaces
  return homeExpanded;
}
```

Resolves the issue:

```bash
$ doctoc Extra\ Headers.md

DocToccing single file "Extra Headers.md" for github.com.

==================

"Extra Headers.md" will be updated

Everything is OK.
```

To resolve:

```js
function cleanPath(path) {
  return homeExpanded = (path.indexOf('~') === 0) ? process.env.HOME + path.substr(1) : path;
}
```

Removed the regex that normalizes the path.

To anyone reading this, if you rely on the fix and you cannot wait for the update please perform the following:

```bash
vim $(which doctoc) +16
```

and edit the code to remove the regex, or just open it up in your favorite code editor:

```bash
code $(which doctoc)
```

**Comment by Shagon94** [comment]
I never got around to creating a pull request, it has been completed - https://github.com/thlorenz/doctoc/pull/163
