### ISSUE TITLE
Invalid TOC generated

### ISSUE THREAD

**Issue by isidore** [thlorenz/doctoc#166]
This is strange, and we played with it a lot and never go a happy answer.
https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/Configuration.md#alternative-base-directory-for-output-file

```md
- [What is configurable?](#what-is-configurable)
- [Using Subdirectories for Approval Output Files](#using-subdirectories-for-approval-output-files)
- [ Alternative Base Directory for Output File](#alternative-base-directory-for-output-file)
- [ PackageLevelSetting](#packagelevelsetting)
```
You'll notice 2 things
There are spaces after the square braces for the last two items
The links don't work...... they are missing the `s` at the end

**Comment by chigh** [comment]
I've got several markdown documents with this same issue. It seems like it's failing (in my document) when semi-colons are involved. As soon as there's a semi-colon in the document, it starts doing this with the next header.

**Comment by AndrewSouthpaw** [comment]
Calling this "won't fix" for now unless someone wants to tackle it?
