### ISSUE TITLE
[Bug?] `--update-only` option doesn't seem to be recognized as of v1.4.0

### ISSUE THREAD

**Issue by PawelLipski** [thlorenz/doctoc#189]
```
$ npm list -g doctoc
/usr/local/lib
└── doctoc@1.4.0 

$ doctoc --update-only
Unknown option(s): --update-only
Usage: doctoc [mode] [--entryprefix prefix] [--notitle | --title title] [--maxlevel level] <path> (where path is some path to a directory (e.g., .) or a file (e.g., README.md))

Available modes are:
  --bitbucket	bitbucket.org
  --nodejs	nodejs.org
  --github	github.com
  --gitlab	gitlab.com
  --ghost	ghost.org
Defaults to 'github.com'.
```

**Comment by AndrewSouthpaw** [comment]
I believe @thlorenz may need to release a new version.

**Comment by AndrewSouthpaw** [comment]
btw I believe you can always point to the git repo itself to get access to the latest, though I understand that can feel brittle. 😄 

```
"my-dep": "git+https://git@github.com/...",
```

In case you were wanting more of an immediate workaround.

**Comment by thlorenz** [comment]
Hey @AndrewSouthpaw, just seeing this.
Is the current master in a state for a new version? And if so should it be a major or minor upgrade following semver?

**Comment by AndrewSouthpaw** [comment]
Thanks @thlorenz. A minor should be fine; I've seen no breaking changes.

**Comment by thlorenz** [comment]
OK published (went for major since there were lots of new features and definitely doesn't hurt a thing).
So 2.0.0 is out, thanks for all the work on this!

**Comment by AndrewSouthpaw** [comment]
Calling this closed.
