### ISSUE TITLE
Migrate Travis-CI.org to Travis-CI.com / Re-enable CI

### ISSUE THREAD

**Issue by PeterDaveHello** [thlorenz/doctoc#227]
Currently, the CI is not running:

https://travis-ci.org/github/thlorenz/doctoc

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

**Comment by PeterDaveHello** [comment]
I personally applied for OSS credits several times with no issue at all, just simply open a support ticket to them, and the credits will be charged, not sure if this info will help?

**Comment by kevin-david** [comment]
@thlorenz I created a PR to migrate to actions here: https://github.com/thlorenz/doctoc/pull/231

Tested in my fork and the tests pass: https://github.com/kevin-david/doctoc/pull/1/checks
