### ISSUE TITLE
Doesn't capture all headings in this file

### ISSUE THREAD

**Issue by jimhigson** [thlorenz/doctoc#24]
Hi,

I just tried using doctoc on the README.md here:

https://github.com/jimhigson/oboe.js/

It only gets so far as the API heading. Otherwise this would be perfect. Is there a design decision to only do the first X headings or is this a bug?

**Comment by rvangundy** [comment]
I'm still seeing this issue happening on the latest version of doctoc I downloaded this evening. There are several sections that aren't being included in the ToC. Here's a gist:

https://gist.github.com/rvangundy/0e13270f00b281f0ae99

**Comment by thlorenz** [comment]
@rvangundy Could you please be more specific about which aren't included.

Even better could you extract a test from this example which currently fails but should pass?
Please add that to the anchor-markdown-header module.

We can then figure out how to make that test pass to solve your issue.
