### ISSUE TITLE
Exclamation marks (!) in headers break toc links

### ISSUE THREAD

**Issue by analog-nico** [thlorenz/doctoc#34]
In my README.md I have e.g.:
# Hi my friend!

Currently, the generated TOC entry will be:
- [Hi my friend!](#hi-my-friend!)

However, the link won't work on GitHub. Exclamation marks must be omitted. The correct TOC entry is:
- [Hi my friend!](#hi-my-friend)

I observed this behavior for exclamation marks at the end of a header as well as in the middle. In both cases they need to be omitted in the anchor.

**Comment by codeblooded** [comment]
This has been filed with [anchor-markdown-header as 12](https://github.com/thlorenz/anchor-markdown-header/issues/12).  We're still experiencing this problem in Quick.
