### ISSUE TITLE
Soft link causes doctoc to crash.

### ISSUE THREAD

**Issue by DanTheColoradan** [thlorenz/doctoc#42]
I have a valid soft link in my directory and when I run doctoc, it says there isn't a directory there and then quits. Let me know if you need anymore info!

**Comment by thlorenz** [comment]
Could you please provide a repo on github that reproduces this?

Make it so in order to repro all I'd have to do is clone the repo followed by:

```
npm install
npm test
```

Thanks.

**Comment by thlorenz** [comment]
Closing feel free to submit a PR that fixes that -- possibly upgrading readdirp and making it use graceful-fs could work.

**Comment by DanTheColoradan** [comment]
Sounds good. Sorry. Been a bit busy :)


————
Daniel L. Polanco
Fledgling Programmer | Perl | C++
719-422-3765 | Website | GitHub | Twitter | Safe Email
————
