### ISSUE TITLE
Feature request: max depth

### ISSUE THREAD

**Issue by Madsn** [thlorenz/doctoc#44]
It would be neat to be able to define a max depth for the headers included in the TOC, passed in as an argument. So a max-depth of 3 would not show `####` headers in the TOC.

I may create a pull request on this eventually, haven't looked at the code yet so not sure how tricky it would be to implement, but figured I would create this feature request for now.

**Comment by thlorenz** [comment]
Shouldn't be too tricky.
[Write a test first](https://github.com/thlorenz/doctoc/blob/master/test/transform.js) and then dive into the code to make it happen (I don't have the bandwidth and if I had would first fix some bugs I'm aware of).

You'd start looking [here](https://github.com/thlorenz/doctoc/blob/fba73a5d1f8000aad5a5f2b03bc4aca6e914a111/lib/transform.js#L28).

I'm not sure however how this would work for processing headers of inlined html or if we'd limit it to only actual markdown headers.

**Comment by thlorenz** [comment]
Should be fixed with 0.12 (see readme).
If not feel free to reopen.
