### ISSUE TITLE
Suggestion: allow passing the TOC title via command-line argument

### ISSUE THREAD

**Issue by mklement0** [thlorenz/doctoc#51]
Currently, the title (header) of the table of contents title is hard-coded to:

> **Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

It would be nice to be able to pass in a custom title; e.g.:

`doctoc --title 'Contents' README.md`

**Comment by thlorenz** [comment]
Sure, open to a PR that adds this.

However once we add more cli args we should switch to using [minimist](https://github.com/substack/minimist) instead of parsing them by hand.

An example of using minimist is [here](https://github.com/thlorenz/wicked/blob/master/bin/wicked.js)

**Comment by mklement0** [comment]
Sounds good; give me a couple of days to take a shot at this.

**Comment by mklement0** [comment]
OK, take a look at #52 - I've taken the liberty of also implementing `--maxlevel` for limiting the TOC entries to a max. heading level.

**Comment by thlorenz** [comment]
Is this all covered in your PR?

**Comment by mklement0** [comment]
Yes, it is, thanks.
