### ISSUE TITLE
Overview of all Files/Sections

### ISSUE THREAD

**Issue by jannickfahlbusch** [thlorenz/doctoc#53]
I don't know if this is already a part of DocTo:

It would be cool to have the ability to generate a seperate file, wich contains all ToCs from the other Files, so that this file could be used as Navigation.

**Comment by thlorenz** [comment]
Not currently supported, but if you have an idea of how this could be implemented please PR and we can discuss.

**Comment by jannickfahlbusch** [comment]
If i could write good JS i would do it. 

I've a basic Idea on how this goal could be achieved, but i have no clue, how i should develop it.

**Comment by thlorenz** [comment]
Good chance to learn JS then ;)

**Comment by thlorenz** [comment]
Waiting for PR, but closing for now.
