### ISSUE TITLE
Add way of checking if existing ToCs need updating

### ISSUE THREAD

**Issue by ExplodingCabbage** [thlorenz/doctoc#54]
I'm not currently a doctoc user, but if I were, one feature I imagine I'd like would be the ability to check whether doctoc needs running. This would be handy as part of a CI test suite to ensure that some careless soul hadn't updated the readme and forgotten to run doctoc.

All the check would need to do is locate all markdown files with a  in them and check that their current content exactly matches what their content *would* be after running doctoc.

**Comment by kookerus** [comment]
That's actually a really great idea. I never thought about it, but that would actually make life a whole hell of a lot easier. I don't have access to a computer this week, but if nobody wants to work on this, I'd love to try and get it working.

**Comment by thlorenz** [comment]
Why not just run doctoc as an automated step to make sure it's always up to date?

**Comment by kookerus** [comment]
Maybe a user may just want to see what needs updating without actually updating? A dry run, of sorts.

**Comment by thlorenz** [comment]
Well if people need that I'm open to a well tested PR.

**Comment by ExplodingCabbage** [comment]
> Why not just run doctoc as an automated step to make sure it's always up to date?

Analogoously you could arguethat there's no need for a linting step that detects trailing whitespace when you could have an automated step that strips trailing whitespace. This is likewise a defensible idea, but the trouble is that if you're relying upon this step being run via a hook on people's dev machines, you have no guarantee it'll get run (since a new contributor might not add the hook), and if you have it done as part of your CI, you need your CI server to be making and pushing commits for you, which isn't something I've ever seen done in the wild, and is more complicated - both to implement and to understand - than simply checking whether something is broken and nagging a human to fix it.

**Comment by thlorenz** [comment]
@ExplodingCabbage not sure why you're still trying to convince me since I already said I'm open to a PR that adds this ;)
