### ISSUE TITLE
Doctoc generating newline in header entries

### ISSUE THREAD

**Issue by fresheneesz** [thlorenz/doctoc#56]
I'm getting markdown that looks like this:

```
](#changelog)
- [How to Contribute!
](#how-to-contribute)
- [License
](#license)
```

From a header that looks like this:

```
`blocks.js`
============
```

This seems to be happening to all my top level headers

**Comment by fresheneesz** [comment]
I'm using the version of doctoc that's currently on npm

**Comment by thlorenz** [comment]
No idea what's going on here. Possibly it's due to the backtick in your title.
This would need to be fixed in anchor-markdown-header.

**Comment by fresheneesz** [comment]
Ok, I'll open an issue there.
