### ISSUE TITLE
Doctoc generates incorrect anchor link when there is a url link in the header

### ISSUE THREAD

**Issue by fresheneesz** [thlorenz/doctoc#57]
For the header:

```
#### Instance properties inherited from [`EventEmitter`](http://nodejs.org/api/events.html)
```

doctoc is generating:

```
[Instance properties inherited from [`EventEmitter`](http://nodejs.org/api/events.html)](#instance-properties-inherited-from-eventemitterhttpnodejsorgapieventshtml)
```

Which doesn't link to the header (tho it does link to EventEmitter)

**Comment by thlorenz** [comment]
Please provide a PR to anchor-markdown-header to fix this.
Thanks.

**Comment by fresheneesz** [comment]
@thlorenz I'll open the issue there. I have a few other repos requesting me to make pull requests, so I don't have time for another one at the moment.

I'd recommend keeping this issue open, tho, until anchor-markdown-header is fixed and pulled into this project.
