### ISSUE TITLE
Script does not generate anchors.

### ISSUE THREAD

**Issue by velthune** [thlorenz/doctoc#60]
This script is nice, but lack of anchors in TOC is, grant me the term, depressing. 
If you add this feature -> 10stars!

**Comment by thlorenz** [comment]
Please be more specific.
What output do you want, what does it output instead?

And BTW it generates markdown anchors not html anchors which is the intent.

**Comment by velthune** [comment]
When I click on a TOC item, I would like to be led to corresponding section.

**Comment by thlorenz** [comment]
Please provide a sample I can see (on github) otherwise I cannot help you.
