### ISSUE TITLE
GitLab mode needs 4-spaces indentation

### ISSUE THREAD

**Issue by mefjuu** [thlorenz/doctoc#61]
GitLab mode needs 4-spaces indentation instead of 2. Otherwise TOC hierarchy is rendered incorrectly.

**Comment by thlorenz** [comment]
PRs welcome.
Most likely a [simple change here](https://github.com/thlorenz/doctoc/blob/master/lib/transform.js#L143) will fix things.

Please make sure to include tests.

**Comment by thlorenz** [comment]
Fixed
