### ISSUE TITLE
Bug For a header with special characters an invalid link is generated

### ISSUE THREAD

**Issue by robwe** [thlorenz/doctoc#63]
For the header
```
# Größe
```
(which is a normal German word) the TOC entry
```
[Größe](#gr%C3%B6%C3%9Fe)
```
is generated in an UTF-8 encoded file, but GitHub expects it to be
```
[Größe](#gr-e)
```

**Comment by thlorenz** [comment]
Please file this issue in [anchor-markdown-header](https://github.com/thlorenz/anchor-markdown-header). I'm not sure how we can fix this since I don't know all the chars that get removed by @github.

It'd be so helpful if @github would open source the code they use to generate the anchors :)
