### ISSUE TITLE
Infer --title

### ISSUE THREAD

**Issue by jez** [thlorenz/doctoc#64]
It'd be awesome if you only had to specify `--title` if

- you're running `doctoc` for the first time, or
- you want to change the title of the ToC

and in other cases (i.e. when the ToC, `START doctoc`, `END doctoc` sections already exist) the title is inferred from the existing ToC

**Comment by thlorenz** [comment]
Sounds like an interesting feature. Open for PR that adds it.
Make sure to include tests ;)
