### ISSUE TITLE
Use anchor IDs without dashes for headers that include spaces.

### ISSUE THREAD

**Issue by bkuhlmann** [thlorenz/doctoc#75]
When generating a TOC for a header that includes spaces, dashes are used in the anchor ID but they should be removed in order for the TOC link to work properly.

For example, if a `README.md` has the following Markdown header:

`# Code of Conduct` 

DocToc will generate the following TOC link:

`[Code of Conduct](#code-of-conduct)`

What should be generated instead is:

`[Code of Conduct](#codeofconduct)`

By not including the dashes, the link will work properly.

**Comment by bkuhlmann** [comment]
Discovered, after deploying code to GitHub, the anchors with dashes work. Prior to deploy, I was testing the functionality within [Marked](http://marked2app.com) (Version 1, not Version 2 which is linked), locally. Maybe upgrading to Version 2 will alleviate this problem, not sure.

Also, confirmed that links without dashes don't work on GitHub.

Closing this issue as I've confirmed the code is working as designed and the problem was with my environment only.

**Comment by mklement0** [comment]
Yes, Marked 2, unlike Marked 1, should be able to mimic GitHub's rendering in all essential aspects (there are still subtle differences), assuming it is configured accordingly, via `Preferences ... > Processor`:

*  CHECK  `Discount (GFM)` 
* UN-check `Retain line breaks in paragraphs`

**Comment by bkuhlmann** [comment]
Thanks, that is helpful.
