### ISSUE TITLE
invalid header comment <-- --> for bitbucket 

### ISSUE THREAD

**Issue by dpinol** [thlorenz/doctoc#83]
Hi,
even when specifying --bitbucket, doctoc generates the header comments with .
Unfortunately, bitbucket markdown does not recognize  and displays the comments

**Comment by jez** [comment]
Does Bitbucket recognize comments at all? If not I don't know if it's worth changing this compared to the benefits of being able to delete the old TOC, etc.

**Comment by dpinol** [comment]
you're right. For anybody interested, please vote their issue! 
https://bitbucket.org/tutorials/markdowndemo/issues/15/how-can-you-insert-comments-in-the#comment-20998909

**Comment by jez** [comment]
Closing as upstream issue.
