### ISSUE TITLE
ignore headers within code blocks 

### ISSUE THREAD

**Issue by dpinol** [thlorenz/doctoc#84]
Hi,
Could the headers within code blocks be ignored? When I run doctoc on input below...

	# hola
	~~~
	# adeu
	~~~

... I get the following, I'd only like to have "hola" at the TOC
~~~
- [hola](#hola)
- [adeu](#adeu)
~~~
thanks

**Comment by jez** [comment]
Yeah, that's an issue we've been aware of for some time. I wouldn't be surprised if #77 fixes it though.

**Comment by jez** [comment]
Closed via #107.
