### ISSUE TITLE
Clicking on links does not take us to the anchor

### ISSUE THREAD

**Issue by mohitathwani** [thlorenz/doctoc#85]
Clicking on the link in the TOC does not take us to the anchor tag in HTML .

**Comment by shanecarmody** [comment]
Hey @mohitathwani, 

How did you manage to resolve this? I’m having the same issue at the moment.

Thanks

**Comment by mohitathwani** [comment]
@shanecarmody make sure you pass the parameter for the git service you are using i.e. github or bitbucket etc..

**Comment by shanecarmody** [comment]
@mohitathwani mine was actually nothing to do with passing a parameter, I’m using **doctoc** with https://github.com/SC5/sc5-styleguide and there must have been a conflict. I’ve since updated SC5 Styleguide and the issue has been resolved. 

Thanks for your help.
