### ISSUE TITLE
doctoc failing with https://github.com/iogf/untwisted/blob/master/BOOK.md

### ISSUE THREAD

**Issue by iogf** [thlorenz/doctoc#99]
When i try to generate toc for https://github.com/iogf/untwisted/blob/master/BOOK.md
it fails with html code inside ~~~python code ~~~.

For example, for the above link it gives me: I have highlighed the wrong parts with <---.

    
    
    **Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*
    
    - [What can i create with untwisted?](#what-can-i-create-with-untwisted)
    - [Untwisted plugins](#untwisted-plugins)
    - [The rapidserv plugin](#the-rapidserv-plugin)
        - [A simple application](#a-simple-application)
        - [The **request** object](#the-request-object)
          - [request.method](#requestmethod)
          - [request.headers](#requestheaders)
          - [request.data](#requestdata)
          - [request.query](#requestquery)
          - [request.path](#requestpath)
          - [request.version](#requestversion)
        - [The basic dir structure](#the-basic-dir-structure)
        - [Quote Application](#quote-application)
          - [quote/static/comment.html](#quotestaticcommenthtml)
          - [quote/templates/show.html](#quotetemplatesshowhtml)
    - [ List of quotes. ](#list-of-quotes)
        - [ {{name}} {{quote}}... ](#name-quote)
    - [ Add quote ](#add-quote)
          - [quote/templates/view.html](#quotetemplatesviewhtml)
    - [ {{name}} ](#name) <--- It shouldnt be here.
        - [ {{quote}} ](#quote) <--- it shouldnt be here.
          - [quote/app.py](#quoteapppy)
          - [Running](#running)
        - [Imup Applicaiton](#imup-applicaiton)
          - [imup/templates/view.jinja](#imuptemplatesviewjinja)
    - [ Upload image ](#upload-image)
    - [ Images ](#images)
        - [ {{index}} ](#index) <--- It shouldnt be here.
    - [ Upload image ](#upload-image-1)
    - [ Images ](#images-1)
        - [ {{index}} ](#index-1)
          - [imup/app.py](#imupapppy)
    - [ Bad request ](#bad-request)
    - [ Bad request ](#bad-request-1)
        - [quickserv script](#quickserv-script)
    - [The requests plugin](#the-requests-plugin)
    - [The event-driven paradigm](#the-event-driven-paradigm)
        - [Skeletons](#skeletons)
        - [Image of objects/handles](#image-of-objectshandles)
        - [The symbol **](#the-symbol-)
        - [Event arguments](#event-arguments)
    - [Dispatcher class](#dispatcher-class)
        - [Event creation](#event-creation)
        - [Spawning events from handles](#spawning-events-from-handles)
        - [Passing additional arguments to handles](#passing-additional-arguments-to-handles)
        - [Unbinding handles](#unbinding-handles)
        - [Exceptions in handles](#exceptions-in-handles)
        - [The Kill, Root exceptions](#the-kill-root-exceptions)
        - [Handle returns](#handle-returns)
        - [Handles that are mapped upon events and produce events.](#handles-that-are-mapped-upon-events-and-produce-events)
        - [Dispatcher flow control](#dispatcher-flow-control)
        - [Static handles](#static-handles)
        - [binding static handles to events](#binding-static-handles-to-events)
        - [Unbinding static handles to events](#unbinding-static-handles-to-events)
    - [Reactors](#reactors)
    - [Super socket class](#super-socket-class)
    - [Spin class](#spin-class)
    - [A word on handles](#a-word-on-handles)
    - [Basic built-in handles](#basic-built-in-handles)
    - [Basic Client/Server Applications](#basic-clientserver-applications)
        - [A simple Client (is_up.py)](#a-simple-client-is_uppy)
        - [Msg Server (msg_server.py)](#msg-server-msg_serverpy)
        - [Msg Client (msg_client.py)](#msg-client-msg_clientpy)
        - [Echo Server (echo_server.py)](#echo-server-echo_serverpy)
    - [Splits](#splits)
        - [Terminator Split](#terminator-split)
        - [Calc Server (calc_server.py)](#calc-server-calc_serverpy)
    - [Timers](#timers)
    - [Coroutines](#coroutines)
        - [A simple chat server (chat_server.py)](#a-simple-chat-server-chat_serverpy)
    - [Threads](#threads)
        - [Job class](#job-class)
        - [A basic example (sum.py)](#a-basic-example-sumpy)
    - [Spawning processes](#spawning-processes)
        - [Expect class](#expect-class)
        - [A basic example (spawn_process.py)](#a-basic-example-spawn_processpy)
    - [Tasks](#tasks)
        - [Task class](#task-class)
        - [A Port Scan (port_scan.py)](#a-port-scan-port_scanpy)
    - [Basic SSL Client/Server Applications](#basic-ssl-clientserver-applications)
    - [The IRC Client plugin](#the-irc-client-plugin)
    - [Reactor flow control](#reactor-flow-control)
        - [The Root exception](#the-root-exception)
        - [The Kill exception](#the-kill-exception)
    - [Debugging](#debugging)
    - [Tests](#tests)

**Comment by jez** [comment]
Closed via #107.
